3DP/Areas/Admin/Models/Entities/Product.cs
using _3DP.Areas.Admin.Constant;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace _3DP.Areas.Admin.Models.Entities
{
    [Table("tb_Products")]
    public class Product
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ProductID { get; set; }

        [Required(ErrorMessage = ErrorMessageConstant.Require)]
        [Display(Name = "Tên")]
        [Column(TypeName = "nvarchar")]
        public string ProductName { get; set; }

        [Required(ErrorMessage = ErrorMessageConstant.Require)]
        [StringLength(20, ErrorMessage = "Tối đa 20 ký tự")]
        [Display(Name = "Mã")]
        [Column(TypeName = "nvarchar")]
        public string ProductCode { get; set; }

        [StringLength(20, ErrorMessage = "Số lượng")]
        [Display(Name = "Số lượng")]
        [Column(TypeName = "nvarchar")]
        public string Quantity { get; set; }

        [Required(ErrorMessage = ErrorMessageConstant.Require)]
        [Display(Name = "Danh mục")]
        [Column(TypeName = "nvarchar")]
        public string CatCode { get; set; }

        [Required(ErrorMessage = ErrorMessageConstant.Require)]
        [Display(Name = "Giá bán")]
        [Column(TypeName = "float")]
        public float Price { get; set; }

        [Required(ErrorMessage = ErrorMessageConstant.Require)]
        [Display(Name = "Khuyễn mãi")]
        [Column(TypeName = "float")]
        public float SalePrice { get; set; }

        [Display(Name = "Ngày nhập")]
        [Column(TypeName = "date")]
        public DateTime CreatetDate { get; set; }

        [Display(Name = "ngày bán")]
        [Column(TypeName = "date")]
        public DateTime SaleDate { get; set; }

        [Required(ErrorMessage = ErrorMessageConstant.Require)]
        [Display(Name = "Hình ảnh")]
        [Column(TypeName = "nvarchar")]
        public string Image { get; set; }
    }
}

3DP/Areas/Admin/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _3DP.Areas.Admin.Models.BusinessModels;
using _3DP.Areas.Admin.Models.Entities;

namespace _3DP.Areas.Admin.Controllers
{
    public class CategoriesController : Controller
    {
        private DBContextCommon db = new DBContextCommon();

        // GET: Admin/Categories
        public ActionResult Index()
        {
            return View("ListCategory", db.DSCategory.ToList());
        }

        // GET: Admin/Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.DSCategory.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Admin/Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CatID,CatCode,CatName,ParentCatCode")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.DSCategory.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);

        }

        // GET: Admin/Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View("DetailCategory", new Category());
            }
            Category category = db.DSCategory.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            category.State = (int)EntityState.Modified;
            return View("DetailCategory", category);
        }
        /// <summary>
        /// Hàm cất chung khi thêm/sửa
        /// </summary>
        /// <param name="category"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save([Bind(Include = "CatID,CatCode,CatName,ParentCatCode,State")] Category category)
        {
            if (ModelState.IsValid)
            {
                if (category.State != (int)EntityState.Modified)
                {
                    db.DSCategory.Add(category);
                }
                else
                {
                    category.ModifyDate = DateTime.Now;
                    db.Entry(category).State = EntityState.Modified;
                }
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        //// GET: Admin/Categories/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Category category = db.DSCategory.Find(id);
        //    if (category == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(category);
        //}

        // POST: Admin/Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            Category category = db.DSCategory.Find(id);
            db.DSCategory.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

3DP/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _3DP.Areas.Admin.Models.BusinessModels;

namespace _3DP.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
        private DBContextCommon db = new DBContextCommon();
        // GET: Admin/Product
        public ActionResult Index()
        {
            return View("ProductList", db.DSProduct.ToList());
        }
    }
}

3DP/Areas/Admin/Views/Product/ProductList.cshtml
@model IEnumerable<_3DP.Areas.Admin.Models.Entities.Product>

@{
    ViewBag.Title = "Danh sách sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ProductList</h2>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <button type="button" class="btn btn-success fa fa-plus" onclick="location.href='@Url.Action( "Create","Product")'"> Thêm</button>
                </div>
                <div class="box-body">
                    <table class="table table-bordered table-striped" id="tbCategories">
                        <thead>
                            <tr class="bg-primary">
                                <th>
                                    @Html.DisplayNameFor(model => model.ProductCode)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ProductName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CatCode)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Quantity)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Image)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ProductID)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ProductName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CatCode)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Quantity)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Image)
                                </td>
                                <td width="230px">
                                    <button type="button" class="btn btn-warning fa fa-pencil" onclick="location.href='@Url.Action( "Edit","Categories",new { id = item.ProductID })'"> Sửa</button>
                                    <button type="button" class="btn btn-info fa fa-eye" onclick="location.href='@Url.Action( "Details","Categories",new { id = item.ProductID })'"> Xem</button>
                                    <button type="button" class="btn btn-danger fa fa-trash" onclick="executeDelete(@item.ProductID)"> Xóa</button>
                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </div>
    </div>
</section>